# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric properties (checked for Minecraft 1.21.11)
minecraft_version=1.21.11
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod properties
mod_version=1.0.0
maven_group=com.prabhas
archives_base_name=skipmenu